In [3]:
import numpy as np
import pandas as pd
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC

import pickle
from sklearn.model_selection import cross_val_score
from sklearn import metrics
from sklearn.base import BaseEstimator, TransformerMixin, ClassifierMixin, clone
from sklearn.model_selection import KFold
from scipy import stats
from scipy.stats import norm, skew 
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.feature_selection import SelectFromModel
import warnings
warnings.filterwarnings('ignore')

C:\Users\krish\AppData\Local\Temp\ipykernel_18936\3013888228.py:2: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [4]:
train = pd.read_csv("D:\Krish\Programs\Mini Project\Traffic.csv")
train
train.head()

,Time,Date,Day of the week,CarCount,BikeCount,BusCount,TruckCount,Total,Traffic Situation
0,12:00:00 AM,10,Tuesday,31,0,4,4,39,low
1,12:15:00 AM,10,Tuesday,49,0,3,3,55,low
2,12:30:00 AM,10,Tuesday,46,0,3,6,55,low
3,12:45:00 AM,10,Tuesday,51,0,2,5,58,low
4,1:00:00 AM,10,Tuesday,57,6,15,16,94,normal

In [5]:
train,test = train_test_split(train,test_size=0.25,random_state=1992)

In [6]:
train.isnull().sum()

Time                 0
Date                 0
Day of the week      0
CarCount             0
BikeCount            0
BusCount             0
TruckCount           0
Total                0
Traffic Situation    0
dtype: int64

In [7]:
test.isnull().sum()

Time                 0
Date                 0
Day of the week      0
CarCount             0
BikeCount            0
BusCount             0
TruckCount           0
Total                0
Traffic Situation    0
dtype: int64

In [8]:
df_temp = train
df_temp['Day of the week'] = df_temp['Day of the week'].replace( {'Monday':1,'Tuesday':2,'Wednesday':3,'Thursday':4,'Friday':5,'Saturday':6,'Sunday':7})
df_temp['Traffic Situation'] = df_temp['Traffic Situation'].replace({'low':1,'normal':2,'high':3,'heavy':4})
df_temp

,Time,Date,Day of the week,CarCount,BikeCount,BusCount,TruckCount,Total,Traffic Situation
194,12:30:00 AM,12,4,18,5,1,13,37,2
1294,11:30:00 AM,23,1,40,9,15,28,92,2
1024,4:00:00 PM,20,5,81,29,5,0,115,2
1242,10:30:00 PM,22,6,14,3,0,33,50,2
1789,3:15:00 PM,28,6,80,26,35,6,147,3
...,...,...,...,...,...,...,...,...,...
1921,12:15:00 AM,30,1,19,2,0,22,43,2
229,9:15:00 AM,12,4,24,18,37,18,97,2
1835,2:45:00 AM,29,7,19,2,1,12,34,1
2216,2:00:00 AM,2,4,12,3,0,39,54,2
2313,2:15:00 AM,3,5,12,3,0,22,37,2

In [9]:
time_train = train
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
time_train['Time'] = le.fit_transform(time_train['Time'])
time_train['Time']

194     20
1294    12
1024    49
1242     5
1789    43
        ..
1921    18
229     90
1835    38
2216    32
2313    34
Name: Time, Length: 2232, dtype: int32

In [10]:
train = train.drop(columns=["Date"],axis=1)
train

,Time,Day of the week,CarCount,BikeCount,BusCount,TruckCount,Total,Traffic Situation
194,20,4,18,5,1,13,37,2
1294,12,1,40,9,15,28,92,2
1024,49,5,81,29,5,0,115,2
1242,5,6,14,3,0,33,50,2
1789,43,6,80,26,35,6,147,3
...,...,...,...,...,...,...,...,...
1921,18,1,19,2,0,22,43,2
229,90,4,24,18,37,18,97,2
1835,38,7,19,2,1,12,34,1
2216,32,4,12,3,0,39,54,2
2313,34,5,12,3,0,22,37,2

In [11]:
X= train.drop(columns=['Traffic Situation'],axis=1)
y= train['Traffic Situation']

In [12]:
X_train = X
y_train = y

In [13]:
X_train,X_eval,y_train,y_eval=train_test_split(X_train,y_train,test_size=0.25,random_state=2019)
print(X_train.shape)
print(X_eval.shape)
print(y_train.shape)
print(y_eval.shape)

(1674, 7)
(558, 7)
(1674,)
(558,)

In [14]:
y_train =pd.DataFrame(y_train)
y_eval =pd.DataFrame(y_eval)
y_train,y_eval

(      Traffic Situation
 854                   2
 2413                  2
 1465                  4
 1592                  2
 2179                  4
 ...                 ...
 421                   2
 1722                  2
 2545                  2
 2832                  2
 186                   2

 [1674 rows x 1 columns],
       Traffic Situation
 495                   2
 2226                  1
 913                   2
 2034                  1
 2475                  2
 ...                 ...
 2134                  2
 445                   2
 1059                  2
 958                   2
 609                   3

 [558 rows x 1 columns])

In [15]:
train

,Time,Day of the week,CarCount,BikeCount,BusCount,TruckCount,Total,Traffic Situation
194,20,4,18,5,1,13,37,2
1294,12,1,40,9,15,28,92,2
1024,49,5,81,29,5,0,115,2
1242,5,6,14,3,0,33,50,2
1789,43,6,80,26,35,6,147,3
...,...,...,...,...,...,...,...,...
1921,18,1,19,2,0,22,43,2
229,90,4,24,18,37,18,97,2
1835,38,7,19,2,1,12,34,1
2216,32,4,12,3,0,39,54,2
2313,34,5,12,3,0,22,37,2

In [16]:
df_test = test
df_test['Day of the week'] = df_test['Day of the week'].replace( {'Monday':1,'Tuesday':2,'Wednesday':3,'Thursday':4,'Friday':5,'Saturday':6,'Sunday':7})
df_test['Traffic Situation'] = df_test['Traffic Situation'].replace({'low':1,'normal':2,'high':3,'heavy':4})
df_test
time_test = test
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
time_test['Time'] = le.fit_transform(time_test['Time'])
time_test['Time']
X_test = test.drop(columns=['Traffic Situation','Date'], axis = 1)
X_test
y_test = test['Traffic Situation']
X_test

      Time  Day of the week  CarCount  BikeCount  BusCount  TruckCount  Total
1338     5                1        12          0         0          22     34
518     92                7        64         12        27           8    111
770     20                3        20          5         0          10     35
308     56                5        58         13         4          15     90
1013    27                5       161         50        10           0    221
...    ...              ...       ...        ...       ...         ...    ...
796     72                3       141         15        21           5    182
1964     8                1        26          8        11          20     65
2688    16                2        17          3         0          20     40
493     42                7        18          3         0          28     49
2821    90                3        72          5        15          20    112

[744 rows x 7 columns]

In [17]:
X_train, y_train

(      Time  Day of the week  CarCount  BikeCount  BusCount  TruckCount  Total
 854     93                3        84         23        19          15    141
 2413    42                6        20          1         0          28     49
 1465    66                3       113         16        50           2    181
 1592    33                4        60         18        21          10    109
 2179    55                3       134         15        29           8    186
 ...    ...              ...       ...        ...       ...         ...    ...
 421     90                6        19          3        29           9     60
 1722     5                5        19          0         1          17     37
 2545    19                7        40          8        12          21     81
 2832    17                3        66          9         6          30    111
 186      5                3        18          2         1          25     46

 [1674 rows x 7 columns],
       Traffic Situation
 854                   2
 2413                  2
 1465                  4
 1592                  2
 2179                  4
 ...                 ...
 421                   2
 1722                  2
 2545                  2
 2832                  2
 186                   2

 [1674 rows x 1 columns])

In [18]:
from sklearn import svm
clf = svm.SVC()
clf.fit(X_train,y_train)

SVC()

In [19]:
y_predict= clf.predict(X_test)

In [20]:
accuracy = accuracy_score(y_test,y_predict)
accuracy

0.8938172043010753

In [21]:
import pickle

filename='Model.pkl'
pickle.dump(clf,open(filename,'wb'))